# Generated by Django 5.2.8 on 2025-12-03 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='resutaurant',
            new_name='restaurant',
        ),
    ]
